### PR TITLE
Use timeclock hours

### PR DESCRIPTION
**Pull request by rsammelson**
Start transition to using timeclock-hours
* This does not yet work
  * Importing timeclock-hours won't work yet
* There will still be an option to use built in hour calculation
  * This is what is currently being used
* This will allow us to use timeclock-hours to generate bar graphs in the future

_Note: **Please use squash and merge**_

### CODE REVIEW

**Comment by NotQuiteApex** [comment]
the project should be self contained, and should not go out of its own directory. this would just make managing files a mess. plus, the current calculation works fine as is.

i do like the idea of generating a default opts.txt, but it should really go into its own pull request.

**Comment by rsammelson** [comment]
The main reason linking this repo to `timelock-hours` is to be able to run `timeclock-hours`' analysis (bar graph, hour totals, ranking) from a button on `timeclock`'s GUI. Because I already want to use `timeclock-hours` in this repo, we should make it an **option** to do total time calculation with `timeclock-hours` in order to keep time calculation consistent. Additionally, the default configuration file uses the built-in time calculation, so this PR only adds the **option** to use `timeclock-hours`.

**Comment by rsammelson** [comment]
@notQuiteApex64 I have moved the default configuration stuff to #10.

**Comment by NotQuiteApex** [comment]
`timeclock-hours` does not have those functions, and even if they did they shouldnt be in a separate repository. if its a part of the program, it should be in the same environment.

**Comment by rsammelson** [comment]
@notQuiteApex64 This is on hold right now, because I will probably move the code from`timeclock-hours` to this repository per your request. However I am going to wait until I get the basic functionality of `timeclock-hours` working.

**Pull request closed without merging**
